name: Pull request

on:
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
      -
        name: Run unit tests
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
          run: docker exec notty python -m unittest discover
